version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-root-activity-alert"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-s4a7bxkophjs"
s3_prefix = "aws-root-activity-alert"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
