AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Monitor the root login and activities by using AWS SAM with Python 3.8
Parameters:
  Channel:
    Description: "The channel of Slack to push the message"
    Type: String
  CloudTrailLogGroup:
    Description: "The name of Cloud Trail log group storing global events"
    Type: String
  CloudTrailLogGroupArn:
    Description: "The ARN of Cloud Trail log group storing global events"
    Type: String

Globals:
  Function:
    Timeout: 3

Resources:
  # Root Activity in region ap-southeast-1
  RootActivityFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: root_activity_alert/
      Handler: root_activity.lambda_handler
      Runtime: python3.8
      Events:
        RootActivityRule:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              detail-type:
                - AWS API Call via CloudTrail
              detail:
                userIdentity:
                  type:
                    - Root
      Environment:
        Variables:
          CHANNEL: !Ref Channel

  # Root Login on global
  RootLoginCloudWatchFilter:
    Type: AWS::Logs::SubscriptionFilter
    Properties:
      FilterPattern: '{$.eventName = "ConsoleLogin" && $.userIdentity.type = "Root"}'
      DestinationArn: !GetAtt
        - RootLoginFunction
        - Arn
      LogGroupName: !Ref CloudTrailLogGroup

  RootLoginFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref RootLoginFunction
      Principal: logs.amazonaws.com
      SourceArn: !Ref CloudTrailLogGroupArn

  RootLoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: root_activity_alert/
      Handler: root_login.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          CHANNEL: !Ref Channel

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  RootActivityFunction:
    Description: "Root Activity Lambda Function ARN"
    Value: !GetAtt RootActivityFunction.Arn
  RootLoginFunction:
    Description: "Root Login Lambda Function ARN"
    Value: !GetAtt RootActivityFunction.Arn
